- name: Install Maven
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: Download Maven Dependencies
  ansible.builtin.shell: mvn clean package ; mv target/{{component}}-1.0.jar {{component}}.jar
  args: 
   chdir: /app

- name: Include Schema Setup 
  ansible.builtin.import_tasks:
    file: schema_setup.yml

- name: Include SystemD
  ansible.builtin.import_tasks:
    file: systemd_setup.yml 