- name: Install Python
  ansible.builtin.yum:
    name: 
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Include app_prerequisites
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: Install Python Dependencies
  ansible.builtin.import_tasks: 
  args: 
    chdir: /app

- name: Include schema schema schema setup 
  ansible.builtin.import_tasks:
    file: systemd_setup.yml